name: release
on:
  push:
    branches: [ main, master ]
  pull_request:
  #  branches: [ main, master ]

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Format
        run: bun run format
      - name: Build app
        run: bun run build
